apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn.yaml
  - cert-manager.yaml
  - clickhouse.yaml
  - cnpg.yaml
  - prometheus-community.yaml
  - grafana.yaml
  - haproxy-tech.yaml
  - metallb.yaml
  - nats.yaml
  - temporal.yaml
  - trino.yaml
  - external-dns.yaml
  # MinIO charts managed by Helmfile
